[package]
name = "discord-bot-rust"
version = "0.1.0"
authors = ["Sunrit Jana <warriordefenderz@gmail.com>"]
edition = "2018"

[dependencies]
serenity = "0.10"
tokio = { version = "1", features = ["full"] }
